/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void fails_sometimes() {
        App classUnderTest = new App();
        java.util.Random random = new java.util.Random();
        assertTrue(randomNum > 5);
    }
}
