source 'https://rubygems.org'

# Specify your gem's dependencies in the gemspec
gem 'rake', '~> 13.0'

group :development, :test do
  gem 'minitest', '~> 5.18'
  gem 'minitest-reporters', '~> 1.7'
end

