# This file was generated by the `rspec --init` command
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

RSpec.configure do |config|
  # Run specs in random order to surface order dependencies
  config.order = :random

  # Enable flags like --only-failures and --next-failure
  config.example_status_persistence_file_path = ".rspec_status"

  # Disable RSpec exposing methods globally on `Module` and `main`
  config.disable_monkey_patching!

  # Enable the focus filter
  config.filter_run_when_matching :focus

  config.expect_with :rspec do |c|
    # Use the expect syntax
    c.syntax = :expect

    # Include a description of the failure
    c.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # Use verifying doubles
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  # Be more verbose when running a single test
  config.default_formatter = 'doc' if config.files_to_run.one?
end

