name: Android Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      cli-version:
        type: string
        required: false
        description:
          The version of `analytics-cli` to use. Defaults to the latest specified in
          `analytis-uploader`.

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
      - uses: actions/checkout@v4

     name: Android CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run tests
      run: ./gradlew test

    - name: Upload JUnit.xml
      if: always()
      run: |
        ./trunk flakytests test \
          --org-url-slug gewenyu99 \
          --token ${{ secrets.TRUNK_API_TOKEN }} \
          --junit-paths ./junit-reports/*.xml \
          --allow-empty-test-results