name: Bazel Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      # trunk-ignore(checkov/CKV_GHA_7)
      cli-version:
        type: string
        required: false
        description:
          The version of `analytics-cli` to use. Defaults to the latest specified in
          `analytis-uploader`.

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bazel
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: run tests
        run: bazel test //src/main:hello_test --nobuild_event_json_file_path_conversion --build_event_json_file=build_events.json
        continue-on-error: true

      - name: Install Trunk
        run:  curl -fsSLO --retry 3 https://trunk.io/releases/trunk && chmod +x ./trunk
      - name: Upload JUnit.xml
        if: always()
        run: |
          ./trunk flakytests upload \
            --org-url-slug gewenyu99 \
            --token ${{ secrets.TRUNK_API_TOKEN }} \
            --bazel-bep-path=build_events.json 
            --allow-empty-test-results \