name: Trunk Code Quality
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        # ... other setup steps
      - run: |
          curl -fsSLO --retry 3 https://trunk.io/releases/trunk 
          chmod +x trunk 
          ./trunk check --ci --ci-progress --github-annotate

        env:
          GITHUB_TOKEN: ${{ github.token }}
      # ... other CI steps
