name: Cypress Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      # trunk-ignore(checkov/CKV_GHA_7)
      cli-version:
        type: string
        required: false
        description:
          The version of `analytics-cli` to use. Defaults to the latest specified in
          `analytis-uploader`.

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cypress
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6


      - name: Install Trunk
        run:  curl -fsSLO --retry 3 https://trunk.io/releases/trunk && chmod +x ./trunk
      - name: Upload JUnit.xml
        if: always()
        run: |
          ./trunk flakytests upload \
            --org-url-slug gewenyu99 \
            --token ${{ secrets.TRUNK_API_TOKEN }} \
            --junit-paths ./junit.xml \
            --allow-empty-test-results \
