name: Playwright Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      # trunk-ignore(checkov/CKV_GHA_7)
      cli-version:
        type: string
        required: false
        description:
          The version of `analytics-cli` to use. Defaults to the latest specified in
          `analytis-uploader`.

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./playwright
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Install Trunk
        run:  curl -fsSLO --retry 3 https://trunk.io/releases/trunk && chmod +x ./trunk
      - name: Upload JUnit.xml
        if: always()
        run: |
          ./trunk flakytests test \
            --org-url-slug real-saas-app \
            --token ${{ secrets.TRUNK_API_TOKEN }} \
            --junit-paths ./junit.xml \
            --allow-empty-test-results \
            pnpm run test
