name: Javascript Tests

on:
  schedule:
    - cron: '0 */6 * * *'
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      # trunk-ignore(checkov/CKV_GHA_7)
      cli-version:
        type: string
        required: false
        description: The version of `analytics-cli` to use. Defaults to the latest specified in `analytis-uploader`.

jobs:
  test:
    name: Build and test
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Show current version of Xcode
        run: xcodebuild -version
      - name: Install Trunk
        run:  curl -fsSLO --retry 3 https://trunk.io/releases/trunk && chmod +x ./trunk
      - name: Upload xcresult
        if: always()
        run: |
          ./trunk flakytests test \
            --org-url-slug real-saas-app \
            --token ${{ secrets.TRUNK_API_TOKEN }} \
            --junit-paths ./junit.xml \
            --allow-empty-test-results \
            xcodebuild test -scheme test -resultBundlePath ./test-results.xcresult
