name: XCResult Tests

on:
  schedule:
    - cron: '0 */6 * * *'
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      # trunk-ignore(checkov/CKV_GHA_7)
      cli-version:
        type: string
        required: false
        description: The version of `analytics-cli` to use. Defaults to the latest specified in `analytis-uploader`.

jobs:
  test:
    name: Build and test
    runs-on: macos-13
    defaults:
      run:
        working-directory: xcode/test
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
           xcodebuild test -scheme testTests -resultBundlePath ./test-results.xcresult

      # - name: Install Trunk
      #   run:  curl -fsSLO --retry 3 https://trunk.io/releases/trunk && chmod +x ./trunk
      # - name: Upload xcresult
      #   if: always()
      #   run: |
      #     ./trunk flakytests upload \
      #       --org-url-slug real-saas-app \
      #       --token ${{ secrets.TRUNK_API_TOKEN }} \
      #       --xcresult-path ./test-results.xcresult \
      #       --allow-empty-test-results \
           